function tbl = tblSetTimeZone(tbl, timeZoneStr)
    %TBLSETTIMEZONE Finds variables of the class datetime and in all of them sets the TimeZone property
    arguments (Input)
        tbl
        timeZoneStr
    end
    arguments (Output)
        tbl
    end
    %%% Generated by Copilot
    % Find which table variables are datetime
    isDT = varfun(@isdatetime, tbl, 'OutputFormat', 'uniform');
    % Get their names and set TimeZone for each
    dtNames = tbl.Properties.VariableNames(isDT);
    for k = 1:numel(dtNames)
        name = dtNames{k};
        dt = tbl.(name);
        dt.TimeZone = timeZoneStr;
        tbl.(name) = dt;
    end
    %%%
end