function tf = dtIsAmbiguous(t)
    % Generated by Copilot
    % t must be a scalar datetime with a nonempty TimeZone
    if isempty(t.TimeZone)
        error('Datetime must have a TimeZone.');
    end
    tz = t.TimeZone;
    
    % Use the local wall-clock string to compare
    fmt = t.Format;
    if isempty(fmt), fmt = 'yyyy-MM-dd HH:mm:ss'; end
    localStr = char(t); % representation uses t.Format
    
    % Build a UTC search window ±90 minutes around the nominal UTC instant
    % First interpret t as if it is the instant MATLAB chose currently
    u = datetime(t,'TimeZone','UTC');           % the instant MATLAB currently represents
    uStart = u - minutes(90);
    uEnd   = u + minutes(90);
    
    % sample UTC instants at 1-minute resolution and map to local zone
    uSamples = uStart:minutes(1):uEnd;
    localSamples = datetime(uSamples,'TimeZone','UTC');
    localSamples.TimeZone = tz;                 % view each instant in the target zone
    
    % Count how many distinct UTC instants map to the same local string
    matches = strcmp(cellstr(char(localSamples)), localStr);
    tf = nnz(matches) > 1;
end
